apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvcapp
  template:
    metadata:
      labels:
        app: mvcapp
    spec:
      containers:
      - name: mvcapp
        image: mvcapp:v1   # If using Minikube
        # image: yourdockerhubusername/mvcapp:v1  # If using Docker Hub
        imagePullPolicy: Never   # Use only for Minikube
        ports:
        - containerPort: 5000